config/routes.rb
Rails.application.routes.draw do
  get 'bridge_api_account/refresh'
  get 'bridge_api_callback/item_refresh'
  get 'transactions/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'
  resources :users # generate all CRUD links
  resources :transactions # generate all CRUD links
  post '/transactions/:id/pristine', to: 'transactions#set_pristine'

  resources :bridge_api_items # generate all CRUD links

  get '/users/:id/connect', to: 'users#connect_bridgeapi_item'
  get '/me', to: 'users#me'

  post '/callback/bridgeapi', to: 'bridge_api_callback#callback_handler'
  resources :bridge_api_accounts # generate all CRUD links
  post '/bridge_api_accounts/:id/refresh', to: 'bridge_api_account#refresh'
  post '/bridge_api_accounts/:id/scratch', to: 'bridge_api_account#scratch'
end

app/models/user.rb
require 'bridgeapi/client'

class User < ApplicationRecord
  has_many :bridge_api_items, dependent: :destroy
  has_many :bridge_api_access_tokens, dependent: :destroy

  has_many :bridge_api_accounts, through: :bridge_api_items

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
  validates :bridgeapi_password, presence: true, length: { minimum: 10 }
  validates :bridgeapi_uuid, presence: true, length: { minimum: 10 }

  def valid_access_token
    my_tokens = bridge_api_access_tokens
    if my_tokens.any?
      my_tokens.first.refreshed_value
      return my_tokens.first
    end

    token = BridgeApiAccessToken.new(username: email, password: bridgeapi_password, user: self)
    token.refresh!
    raise 'Impossible to save access token' unless token.save

    token
  end

  # @return [Hash] with a redirect_url key
  def connect_new_bridgeapi_item
    client = BridgeApi::Dependencies.resolve(:client)
    client.connect_new_account(token: valid_access_token)
  end

  def all_transactions(since)
    bridge_api_items.flat_map(&:bridge_api_accounts).flat_map(&:transactions).sort_by(&:date).select { |t| t.date >= since }
  end

  def report(transactions)
    lines = []
    total_co2_kg = 0
    transactions.each do |transaction|
      total_co2_kg += transaction.co2_kg || 0
    end

    lines << "Estimated CO2 footprint: #{total_co2_kg.round(0)}kg"

    accounted_euros = transactions.reject { |t| t.instance_of?(Transaction) }.map { |t| t.amount.abs }.sum
    total_euros = transactions.map { |t| t.amount.abs }.sum
    total_euros = 1 if total_euros.zero?

    accounted_transactions = transactions.reject { |t| t.instance_of?(Transaction) }.count
    total_count = [transactions.count, 1].max

    lines << <<~MSG
      This method accounts for #{(accounted_transactions.to_f / total_count * 100).round(0)}% of expanses (and #{(accounted_euros / total_euros * 100).round(0)}% of total value)
    MSG

    largest_without_estimation = transactions.select { |t| t.instance_of?(Transaction) }.max_by { |t| t.amount.abs }
    lines << "Largest transaction without impact estimation: #{largest_without_estimation}"
    lines
  end
end

app/controllers/users_controller.rb
require 'bridgeapi/client'

class UsersController < ApplicationController
  def index
    authorize(User)
    @users = User.all
  end

  def me
    # we should detect current user here (or at least redirect to the correct "show" invocation)
    username = request.headers['HTTP_REMOTE_USER']
    user = User.find_by(username: username)
    if user
      redirect_to(action: :show, id: user.id)
    else
      redirect_to(new_user_path, notice: "You don't have a user at the moment")
    end
  end

  def show
    @user = User.find(params[:id])
    authorize(@user)
  end

  def destroy
    @user = User.find(params[:id])
    authorize(@user)

    client = BridgeApi::Dependencies.resolve(:client)
    # delete on bridgeapi
    client.delete_user(@user.bridgeapi_uuid, @user.bridgeapi_password)

    @user.destroy

    redirect_to(root_path, status: :see_other)
  end

  def new
    @user = User.new
  end

  def create
    client = BridgeApi::Dependencies.resolve(:client)
    email = "#{params[:user][:username]}@#{ENV['EXPOSED_HOST']}"
    authorize(User.new(username: params[:user][:username])) # we need to authorize before the call to bridgeapi
    new_user = client.create_user(email)
    @user = User.new(
      username: params[:user][:username],
      bridgeapi_password: new_user['password'],
      bridgeapi_uuid: new_user['uuid'],
      email: email
    )

    if @user.save
      redirect_to(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def connect_bridgeapi_item
    # FIXME: [security] we should validate we are allowed to create a new account
    user = User.find(params[:id])
    authorize(user)
    connect_response = user.connect_new_bridgeapi_item
    redirect_to(connect_response['redirect_url'], status: :see_other, allow_other_host: true)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<%= link_to(new_user_path) do %>
  <button type="button" class="btn btn-primary">Create user</button>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Username</th>
      <th scope="col">BridgeAPI UUID</th>
      <th scope="col">BridgeAPI Password</th>
      <th scope="col">Links</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.id %></th>
        <td><%= user.username %></td>
        <td><%= user.bridgeapi_uuid %></td>
        <td>xxxxxx</td>
        <td>
          <%= link_to("View", user)%>
          <%= link_to("Delete", user, data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure to delete #{user.username} forever?"
          })%>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/me.html.erb
 <!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>You</title>
  </head>
  <body>
    <h1>Users#me</h1>
    <p>Find me in app/views/users/me.html.erb</p>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/new.html.erb
<h1>Hello <%= request.headers['HTTP_REMOTE_NAME'] || request.headers['HTTP_REMOTE_USER'] %>!</h1>

You can create an account on this website. In practice it will create a user for this application on the bridge api.
There is no password required because you are already authenticated.

<% default_username = request.headers['HTTP_REMOTE_USER'] || 'unknown' %>

<%= form_with model: @user do |form| %>
  <div class="mb-3 form-floating">
    <%= form.text_field(:username, class: 'form-control', placeholder: default_username) %>
    <label for="user_username" class="form-label">Username</label>
    <% @user.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Account</h1>
Your are <%= @user.username %><br/>
<%= link_to(user_path(@user), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure to delete the data #{@user.username} forever?"
}) do%><button type="button" class="btn btn-danger">Destroy</button><% end %>
your data on this website.
<br/>
<br/>
<%= link_to("#{user_path(@user)}/connect", data: {
  user_id: @user.id
}) do %>
<button type="button" class="btn btn-success">Connect new bank</button>
<% end %>
<h1>Connected banks</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Item ID</th>
      <th scope="col">Bank</th>
      <th scope="col">Status</th>
      <th scope="col">Comment</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @user.bridge_api_items.each do |item| %>
    <tr>
      <th scope="row"><%= item.id %></th>
      <td><%= item.bank_name %></td>
      <td>
        <% if item.status.zero? %>
          ✅
        <% else %>
          ❌ (code: <%= item.status %>)
        <% end %>
      </td>
      <td><%= item.status_code_info %>: <%= item.status_code_description %></td>
      <td scope="row">
      <%= link_to(bridge_api_item_path(item), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure to delete this bank, its account and transactions forever?"
      }) do %>
      <button type="button" class="btn btn-danger">Destroy</button>
      <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%
  transactions = []
  transactions = @user.all_transactions(Time.now - 6 * 30 * 86400)
%>

<h1>Report</h1>
<% @user.report(transactions).each do |line| %>
  <%= line %><br/>
<% end %>

<h1>Transactions</h1>
<table id="transactions" class="table">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Description</th>
      <th scope="col">Category</th>
      <th scope="col">Amount</th>
      <th scope="col">CO2 estimation</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% transactions.each do |transaction| %>
    <tr>
      <td scope="row"><%= transaction.date %></td>
      <td scope="row">
        <%= transaction.icon %> <%= transaction.description %> 
      </td>
      <td scope="row">
        <div data-bs-toggle="tooltip" title="id: <%= transaction.category_id %>"><%= transaction.category_name %></div>
      </td>
      <td scope="row"><%= transaction.full_amount %></td>
      <td scope="row">
        <% if transaction.co2_kg %>
          <% if transaction.explaination_html %>
          <div data-bs-html="true" data-bs-toggle="tooltip" title="<%= transaction.explaination_html %>">
          <% else %>
            <div>
          <% end %>
          <%= transaction.co2_kg.round(2) %>kg
          </div>
        <% else %>
          ❓
        <% end %>
      </td>
      <td scope="row">
      <%= link_to(transaction_path(transaction)) do %>
        <i class="bi-pencil" role="img" aria-label="Edit"></i>
      <% end %>
      <% if transaction.user_updated? %>
        <%= button_to("Reset", "#{transaction_path(transaction)}/pristine", remote: true) %>
      <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<h1>Debug information</h1>
<br/>

Existing tokens: <%= @user.bridge_api_access_tokens.size %>
<br/>
<ul>
  <% @user.bridge_api_access_tokens.each do |token| %>
    <li>expiration <%= token.expires_at %></li>
  <% end %>
</ul>
<br/>
<h1>Known bank accounts</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Account</th>
      <th scope="col">Last refreshed successfully</th>
      <th scope="col">Nb transactions</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @user.bridge_api_accounts.each do |account| %>
    <tr>
      <th scope="row">
        <div data-bs-toggle="tooltip" title="id: <%= account.id %>">
          <%= account.name %> (<%= account.bridge_api_item.bank_name %>)
        </div>
      </th>
      <td><%= account.last_successful_fetch %></td>
      <td><%= account.transactions.count %></td>
      <td>
      <%= button_to("Manual refresh", "#{bridge_api_account_path(account)}/refresh", remote: true) %>
      <%= button_to("Synchronize from scratch", "#{bridge_api_account_path(account)}/scratch", remote: true) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>